### ISSUE TITLE
原稿ディレクトリが `episodes` の決め打ちは不便

### ISSUE THREAD

**Issue by ouvill** [8amjp/novel-builder#1]
原稿を入れるディレクトリが `episodes` ディレクトリ固定だと、汎用性が低く不便です。
`package.json` の `config` で原稿ディレクトリを指定できるようにしませんか？

**Comment by ouvill** [comment]
以下のコミットで対応していただけたのでクローズします。ありがとうございました。

90cd777669817b7e293a465398d41b5ab20e2663

**Comment by 8amjp** [comment]
本日公開したv0.4.4で対応いたしました。ご意見ありがとうございます！
